import React from "react";
import Head from "next/head";
import AuthStatus from "components/AuthStatus";
import { Button, Link } from "@acme/ui";
import Image from "next/image";

const Home = () => {
  return (
    <>
      <Head>
        <title>my-t3-boilerplate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex gap-x-4">
          <Button>Test button</Button>
          <Button
            component={Link}
            href="https://www.google.com"
            external
            variant="secondary"
          >
            As Link
          </Button>
        </div>
        <div>
          <Image
            className="h-[200px] object-cover"
            src="https://images.pexels.com/photos/847393/pexels-photo-847393.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
            alt="This"
            width={800}
            height={200}
          />
        </div>
        <div className="flex min-h-screen w-full flex-col items-center justify-center">
          <h1 className="text-4xl font-bold">my-t3-boilerplate</h1>
          <AuthStatus />
        </div>
      </main>
    </>
  );
};

export default Home;
